site_name: Utility Library
site_url: https://example.com/

theme:
  name: material
  logo: assets/images/Utility.png
  favicon: assets/images/Utility.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - ovveride/highlight.css
  - ovveride/style.css

extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - ovveride/highlight_.js

nav:
    - Home: 'index.md'
    - 'Client':
        - 'Emitter (Start here!)': 
          - 'Info': 'client/emitter/Info.md'
          - 'On': 'client/emitter/On.md'
        - 'Native': 
          - 'Loop':
            - 'CreateLoop': "client/native/CreateLoop.md"
            - '_break': "client/native/_break.md"
            - 'LoopThread': "client/native/LoopThread.md"
            - 'StopLoopThread': "client/native/StopLoopThread.md"
            - 'ResumeLoopThread': "client/native/ResumeLoopThread.md"
          - 'Improved Native':
            - 'CreateObject' : "client/native/CreateObject.md"
            - 'CreateVehicle' : "client/native/CreateVehicle.md"
            - 'DeleteEntity' : "client/native/DeleteEntity.md"
            - 'DisableControlAction' : "client/native/DisableControlAction.md"
            - 'GetPlayerName' : "client/native/GetPlayerName.md"
            - 'IsControlJustPressed' : "client/native/IsControlJustPressed.md"
            - 'PlayerPedId' : "client/native/PlayerPedId.md"
            - 'RegisterNetEvent' : "client/native/RegisterNetEvent.md"
            - 'TaskPlayAnim' : "client/native/TaskPlayAnim.md"
            - 'VehicleDriveToCoord' : "client/native/VehicleDriveToCoord.md"

          - 'Utility Native':
            - 'ShowNotification' : "client/native/ShowNotification.md"
            - 'ButtonNotification' : "client/native/ButtonNotification.md"
            - 'DisableControlForSeconds' : "client/native/DisableControlForSeconds.md"
            - 'DrawText3Ds' : "client/native/DrawText3Ds.md"
            - 'GetEntitySurfaceMaterial' : "client/native/GetEntitySurfaceMaterial.md"

            - 'GetWorldClosestPed' : "client/native/GetWorldClosestPed.md"
            - 'GetWorldClosestPlayer' : "client/native/GetWorldClosestPlayer.md"
            - 'MakeEntityFaceEntity' : "client/native/MakeEntityFaceEntity.md"
        - 'Synced Trigger':
          - 'TriggerSyncedEvent': 'client/synced_trigger/TriggerSyncedEvent.md'
        - 'ESX Integration':
          - 'StartESX': 'client/esx_integration/StartESX.md'
          - 'GetDataForJob': 'client/esx_integration/GetDataForJob.md'
          - 'AddItem': 'client/esx_integration/AddItem.md'
          - 'RemoveItem': 'client/esx_integration/RemoveItem.md'
          - 'GetItem': 'client/esx_integration/GetItem.md'
          - 'AddMoney': 'client/esx_integration/AddMoney.md'
          - 'RemoveMoney': 'client/esx_integration/RemoveMoney.md'
        - 'Advance Script Creation':
          - 'TakeObjectOnHand': 'client/advance_script_creation/TakeObjectOnHand.md'
          - 'DropObjectFromHand': 'client/advance_script_creation/DropObjectFromHand.md'
          - 'GetOnHandObject': 'client/advance_script_creation/GetOnHandObject.md'
          - 'SaveDataToDb': 'client/advance_script_creation/SaveDataToDb.md'
          - 'UpdateDataToDb': 'client/advance_script_creation/UpdateDataToDb.md'
          - 'GetDataFromDb': 'client/advance_script_creation/GetDataFromDb.md'
        - 'Managing data':
          - 'SetFor': 'client/managing_data/SetFor.md'
          - 'GetFrom': 'client/managing_data/GetFrom.md'
        - 'Marker, Object and blip':
          - 'Marker' :
            - 'CreateMarker': 'client/marker-object-blip/CreateMarker.md'
            - 'DeleteMarker': 'client/marker-object-blip/DeleteMarker.md'
            - 'SetMarkerType': 'client/marker-object-blip/SetMarkerType.md'
            - 'SetMarkerDirection': 'client/marker-object-blip/SetMarkerDirection.md'
            - 'SetMarkerRotation': 'client/marker-object-blip/SetMarkerRotation.md'
            - 'SetMarkerScale': 'client/marker-object-blip/SetMarkerScale.md'
            - 'SetMarkerColor': 'client/marker-object-blip/SetMarkerColor.md'
            - 'SetMarkerAlpha': 'client/marker-object-blip/SetMarkerAlpha.md'
            - 'SetMarkerAnimation': 'client/marker-object-blip/SetMarkerAnimation.md'
            - 'SetMarkerDrawOnEntity': 'client/marker-object-blip/SetMarkerDrawOnEntity.md'
          - 'Object' :
            - 'CreateiObject' : 'client/marker-object-blip/CreateiObject.md'
            - 'DeleteiObject' : 'client/marker-object-blip/DeleteiObject.md'
          - 'Blip' :
            - 'CreateBlip' : 'client/marker-object-blip/CreateBlip.md' 
          - 'Get and edit':
            - 'RandomId' : 'client/marker-object-blip/RandomId.md'
            - 'SetIdOf' : 'client/marker-object-blip/SetIdOf.md'
            - 'SetTextOf' : 'client/marker-object-blip/SetTextOf.md'
            - 'GetDistanceFrom' : 'client/marker-object-blip/GetDistanceFrom.md'
            - 'GetCoordOf' : 'client/marker-object-blip/GetCoordOf.md'
            - 'DoesExist' : 'client/marker-object-blip/DoesExist.md'
        - 'Camera':
          - 'CreateCamera' : 'client/camera/CreateCamera.md'
          - 'SwitchBetweenCam' : 'client/camera/SwitchBetweenCam.md'
        - 'Misc':
          - 'DevMode' : 'client/misc/DevMode.md'
          - 'ReplaceTexture' : 'client/misc/ReplaceTexture.md'
          - 'string.multigsub' : 'client/misc/string.multigsub.md'
          - 'table.clone' : 'client/misc/table.clone.md'
          - 'table.empty' : 'client/misc/table.empty.md'
          - 'table.fexist' : 'client/misc/table.fexist.md'
          - 'table.remove' : 'client/misc/table.remove.md'
    - 'Server':          
      - 'RegisterServerEvent' : 'server/RegisterServerEvent.md'
      - 'ShowNotification' : 'server/ShowNotification.md'
      - 'StartESX' : 'server/StartESX.md'
      - 'string.multigsub' : 'server/string.multigsub.md'
      - 'table.clone' : 'server/table.clone.md'
      - 'table.empty' : 'server/table.empty.md'
      - 'table.fexist' : 'server/table.fexist.md'
      - 'table.remove' : 'server/table.remove.md'

markdown_extensions:
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.progressbar
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences