site_name: Utility Library
site_url: https://example.com/

repo_url: https://github.com/utility-library/utility_lib
repo_name: utility-library/documentation

edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/images/Utility.png
  favicon: assets/images/Utility.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - ovveride/highlight.css
  - ovveride/style.css

extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://code.jquery.com/jquery-3.6.0.min.js
  - ovveride/highlight_.js

nav:
    - Home: 'index.md'
    - 'Client':
        - 'Emitter (Start here!)': 
          - 'Info': 'client/emitter/Info.md'
          - 'On': 'client/emitter/On.md'
        - 'Native': 
          - 'Loop':
            - 'CreateLoop': "client/native/CreateLoop.md"
            - 'PauseLoop': "client/native/PauseLoop.md"
            - 'ResumeLoop': "client/native/ResumeLoop.md"
            - 'StopLoop': "client/native/StopLoop.md"
          - 'Improved Native':
            - 'CreateObject' : "client/native/CreateObject.md"
            - 'CreatePed' : "client/native/CreatePed.md"
            - 'CreateVehicle' : "client/native/CreateVehicle.md"
            - 'DeleteEntity' : "client/native/DeleteEntity.md"
            - 'DisableControlAction' : "client/native/DisableControlAction.md"
            - 'GetPlayerName' : "client/native/GetPlayerName.md"
            - 'IsControlJustPressed' : "client/native/IsControlJustPressed.md"
            - 'PlayerPedId' : "client/native/PlayerPedId.md"
            - 'RegisterNetEvent' : "client/native/RegisterNetEvent.md"
            - 'TaskEasyPlayAnim' : "client/native/TaskEasyPlayAnim.md"
            - 'TaskPlayAnim' : "client/native/TaskPlayAnim.md"
            - 'TaskVehicleDriveToCoord' : "client/native/TaskVehicleDriveToCoord.md"
          - 'Utility Native':
            - 'ButtonFor' : "client/native/ButtonFor.md"
            - 'ButtonNotification' : "client/native/ButtonNotification.md"
            - 'CreateMissionText' : "client/native/CreateMissionText.md"
            - 'DisableControlForSeconds' : "client/native/DisableControlForSeconds.md"
            - 'DrawText3Ds' : "client/native/DrawText3Ds.md"
            - 'GenerateRandomCoords' : "client/native/GenerateRandomCoords.md"
            - 'GetEntitySurfaceMaterial' : "client/native/GetEntitySurfaceMaterial.md"
            - 'GetLoadoutOfPed' : "client/native/GetLoadoutOfPed.md"
            - 'GetWorldClosestPed' : "client/native/GetWorldClosestPed.md"
            - 'GetWorldClosestPlayer' : "client/native/GetWorldClosestPlayer.md"
            - 'InTimeRange' : "client/native/InTimeRange.md"
            - 'IsEntityFrozen' : "client/native/IsEntityFrozen.md"
            - 'IsInRadius' : "client/native/IsInRadius.md"
            - 'IsNearCoords' : "client/native/IsNearCoords.md"
            - 'MakeEntityFaceEntity' : "client/native/MakeEntityFaceEntity.md"
            - 'SetPedStatic' : "client/native/SetPedStatic.md"
            - 'SetVehicleWheelsPowered' : "client/native/SetVehicleWheelsPowered.md"
            - 'ShowNotification' : "client/native/ShowNotification.md"
            - 'WaitNear' : "client/native/WaitNear.md"
            - 'Slice System':
              - GetEntitySlice: "client/native/slice_system/GetEntitySlice.md"
              - GetPlayerSlice: "client/native/slice_system/GetPlayerSlice.md"
              - GetSelfSlice: "client/native/slice_system/GetSelfSlice.md"
              - GetSliceCoordsFromCoords: "client/native/slice_system/GetSliceCoordsFromCoords.md"
              - GetSliceFromCoords: "client/native/slice_system/GetSliceFromCoords.md"
              - Integration in other scripts: "client/native/slice_system/Integration.md"
              - IsOnScreen: "client/native/slice_system/IsOnScreen.md"
              - SetSliceUsed: "client/native/slice_system/SetSliceUsed.md"
              - SliceUsed: "client/native/slice_system/SliceUsed.md"
        - 'ESX Integration':
          - 'StartESX': 'client/esx_integration/StartESX.md'
          - 'GetDataForJob': 'client/esx_integration/GetDataForJob.md'
        - 'Advance Script Creation':
          - 'Nui3D' :
            - 'CreateNui3d': 'client/advance_script_creation/n3d/CreateNui3d.md'
            - 'N3d Class Methods': 'client/advance_script_creation/n3d/N3dClass.md'

          - 'Sync':
            - 'TriggerSyncedEvent': 'client/advance_script_creation/sync/TriggerSyncedEvent.md'
            - 'Synced': 'client/advance_script_creation/sync/Synced.md'

          - 'Object': 
            - 'DropObjectFromHand': 'client/advance_script_creation/DropObjectFromHand.md'
            - 'GetOnHandObject': 'client/advance_script_creation/GetOnHandObject.md'
            - 'TakeObjectOnHand': 'client/advance_script_creation/TakeObjectOnHand.md'

          - 'Direction':
            - 'GetDirectionFromVectors': 'client/advance_script_creation/GetDirectionFromVectors.md'
            - 'RotationToDirection': 'client/advance_script_creation/RotationToDirection.md'

          - 'Animation':
            - 'TranslateZAnimated': 'client/advance_script_creation/TranslateZAnimated.md'

          - 'Dialogue':
            - 'EditDialogue': 'client/advance_script_creation/EditDialogue.md'
            - 'IsEntityOnDialogue': 'client/advance_script_creation/IsEntityOnDialogue.md'
            - 'StartDialogue': 'client/advance_script_creation/StartDialogue.md'
            - 'StopDialogue': 'client/advance_script_creation/StopDialogue.md'
        - 'Managing data':
          - 'SetFor': 'client/managing_data/SetFor.md'
          - 'GetFrom': 'client/managing_data/GetFrom.md'
        - 'Marker, Object and blip':
          - 'Marker' :
            - 'CreateMarker': 'client/marker-object-blip/CreateMarker.md'
            - 'DeleteMarker': 'client/marker-object-blip/DeleteMarker.md'
            - 'Set3dText': 'client/marker-object-blip/Set3dText.md'
            - 'Set3dTextDrawRect': 'client/marker-object-blip/Set3dTextDrawRect.md'
            - 'Set3dTextFont': 'client/marker-object-blip/Set3dTextFont.md'
            - 'Set3dTextScale': 'client/marker-object-blip/Set3dTextScale.md'
            - 'SetMarker': 'client/marker-object-blip/SetMarker.md'

            - 'SetMarkerAlpha': 'client/marker-object-blip/SetMarkerAlpha.md'
            - 'SetMarkerAnimation': 'client/marker-object-blip/SetMarkerAnimation.md'

            - 'SetMarkerCoords': 'client/marker-object-blip/SetMarkerCoords.md'
            - 'SetMarkerRenderDistance': 'client/marker-object-blip/SetMarkerRenderDistance.md'
            - 'SetMarkerInteractionDistance': 'client/marker-object-blip/SetMarkerInteractionDistance.md'

            - 'SetMarkerColor': 'client/marker-object-blip/SetMarkerColor.md'
            - 'SetMarkerDirection': 'client/marker-object-blip/SetMarkerDirection.md'
            - 'SetMarkerDrawOnEntity': 'client/marker-object-blip/SetMarkerDrawOnEntity.md'
            - 'SetMarkerRotation': 'client/marker-object-blip/SetMarkerRotation.md'
            - 'SetMarkerScale': 'client/marker-object-blip/SetMarkerScale.md'
            - 'SetMarkerType': 'client/marker-object-blip/SetMarkerType.md'
          - 'Object' :
            - 'CreateiObject' : 'client/marker-object-blip/CreateiObject.md'
            - 'DeleteiObject' : 'client/marker-object-blip/DeleteiObject.md'
          - 'Blip' :
            - 'CreateBlip' : 'client/marker-object-blip/CreateBlip.md' 
            - 'CreateJobBlip' : 'client/marker-object-blip/CreateJobBlip.md' 
          - 'Get and edit':
            - 'DoesExist' : 'client/marker-object-blip/DoesExist.md'
            - 'GetCoordOf' : 'client/marker-object-blip/GetCoordOf.md'
            - 'GetDistanceFrom' : 'client/marker-object-blip/GetDistanceFrom.md'
            - 'RandomId' : 'client/marker-object-blip/RandomId.md'
            - 'SetIdOf' : 'client/marker-object-blip/SetIdOf.md'
        - 'Camera':
          - 'CreateCamera' : 'client/camera/CreateCamera.md'
          - 'SwitchBetweenCam' : 'client/camera/SwitchBetweenCam.md'
        - 'Misc':
          - 'AddPercentage' : 'client/misc/AddPercentage.md'
          - 'DevMode' : 'client/misc/DevMode.md'
          - 'FindInTable' : 'client/misc/FindInTable.md'
          - 'GetRandom' : 'client/misc/GetRandom.md'
          - 'Probability' : 'client/misc/Probability.md'
          - 'RemovePercentage' : 'client/misc/RemovePercentage.md'
          - 'ReplaceTexture' : 'client/misc/ReplaceTexture.md'
          - 'apairs' : 'client/misc/apairs.md'
          - 'printd' : "client/misc/printd.md"
          - 'string.multigsub' : 'client/misc/string.multigsub.md'
          - 'table.clone' : 'client/misc/table.clone.md'
          - 'table.empty' : 'client/misc/table.empty.md'
          - 'table.fexist' : 'client/misc/table.fexist.md'
          - 'table.remove' : 'client/misc/table.remove.md'
    - 'Server':    
      - "Native" : 
        - 'Loop':
          - 'CreateLoop': "server/native/CreateLoop.md"
        - 'RegisterServerEvent': "server/native/RegisterServerEvent.md"
        - 'ShowNotification': "server/native/ShowNotification.md"
      - "MySQL" :
        - 'StartMySQL' : 'server/mysql/StartMySQL.md'
        - 'ExecuteSql' : 'server/mysql/ExecuteSql.md'
      - 'ESX Integration':
        - 'StartESX': 'server/esx_integration/StartESX.md'
        - 'GetDataForJob': 'server/esx_integration/GetDataForJob.md'
        - 'xPlayer':
          - 'AddItem': 'server/esx_integration/xplayer/AddItem.md'
          - 'AddMoney': 'server/esx_integration/xplayer/AddMoney.md'
          - 'GetItem': 'server/esx_integration/xplayer/GetItem.md'
          - 'HaveItem': 'server/esx_integration/xplayer/HaveItem.md'
          - 'HaveItemQuantity': 'server/esx_integration/xplayer/HaveItemQuantity.md'
          - 'HaveMoney': 'server/esx_integration/xplayer/HaveMoney.md'
          - 'RemoveItem': 'server/esx_integration/xplayer/RemoveItem.md'
          - 'RemoveMoney': 'server/esx_integration/xplayer/RemoveMoney.md'
        - 'Society':
          - 'SocietyAddItem': 'server/esx_integration/society/SocietyAddItem.md'
          - 'SocietyAddMoney': 'server/esx_integration/society/SocietyAddMoney.md'
          - 'SocietyGetItem': 'server/esx_integration/society/SocietyGetItem.md'
          - 'SocietyHaveItem': 'server/esx_integration/society/SocietyHaveItem.md'
          - 'SocietyHaveItemQuantity': 'server/esx_integration/society/SocietyHaveItemQuantity.md'
          - 'SocietyHaveMoney': 'server/esx_integration/society/SocietyHaveMoney.md'
          - 'SocietyRemoveItem': 'server/esx_integration/society/SocietyRemoveItem.md'
          - 'SocietyRemoveMoney': 'server/esx_integration/society/SocietyRemoveMoney.md'
      - 'Misc':
        - 'printd' : "server/misc/printd.md"
        - 'string.multigsub' : 'server/misc/string.multigsub.md'
        - 'table.clone' : 'server/misc/table.clone.md'
        - 'table.empty' : 'server/misc/table.empty.md'
        - 'table.fexist' : 'server/misc/table.fexist.md'
        - 'table.remove' : 'server/misc/table.remove.md'

markdown_extensions:
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - minify:
      minify_html: true